# Generated by Django 4.1.5 on 2023-01-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUsuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.usuario',),
        ),
    ]
